name: Sync schema
on:
  workflow_dispatch:


jobs:
  release:
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/update-server-side-sdk-schema.yml@feature/changesets-action
    with:
      tag: v1.1.0
      language: node
      language-version: 21
      generate-command: 'pnpm generateTypes'
      schema-path: resources/fingerprint-server-api.yaml
      examples-path: tests/mocked-responses-tests/mocked-responses-data
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
